# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1918a314e58de873fccec4a48760c95d5c421f8d107eff549d8520139f983e67d75fa85f3b31f78a8ad11e92e11636fda9b7202920f6be4e31a9cd013232329d

test:
  secret_key_base: e9ab8aa44e64d52449b610cf42eb563fdbdb320d1e31a9a95c1ca17d593fe5ff193cfcb4e45ce9dd780b40128ce98963d80cf60e7630c05d3bbbafd6ee8fd419

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
